name: aria2
description: An aria2 api package developed with dart which can be used in a flutter project, support http and websocket connection to an aria2 jsonrpc server.
version: 0.1.3
homepage: https://github.com/fengqiaozhu/aria2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.5.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_model: ^1.0.0
  json_serializable: ^6.8.0

flutter:
